language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update && composer --version
  - composer require --prefer-source satooshi/php-coveralls 0.6.*
  - cd tests

script:
  - phpunit --coverage-clover clover.xml

after_script:
  - cd ..
  - php vendor/bin/coveralls

